export const constructors = [
  {
    id: "mercedes",
    name: "Mercedes",
    // image: require("../assets/constructors/mercedes.png"),
    drivers: ["russell", "antonelli"],
    color: "#00D2BE",
  },
  {
    id: "red_bull",
    name: "Red Bull",
    // image: require("../assets/constructors/red_bull.png"),
    drivers: ["max_verstappen", "tsunoda"],
    color: "#4781D7",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    // image: require("../assets/constructors/ferrari.png"),
    drivers: ["leclerc", "hamilton"],
    color: "#DC0000",
  },
  {
    id: "mclaren",
    name: "McLaren",
    // image: require("../assets/constructors/mclaren.png"),
    drivers: ["piastri", "norris"],
    color: "#F58020",
  },
  {
    id: "aston_martin",
    name: "Aston Martin",
    // image: require("../assets/constructors/aston_martin.png"),
    drivers: ["stroll", "alonso"],
    color: "#239971",
  },
  {
    id: "williams",
    name: "Williams",
    // image: require("../assets/constructors/williams.png"),
    drivers: ["sainz", "albon"],
    color: "#1868DB",
  },
  {
    id: "alpine",
    name: "Alpine",
    // image: require("../assets/constructors/alpine.png"),
    drivers: ["gasly", "colapinto"],
    color: "#00A1E8",
  },
  {
    id: "haas",
    name: "Haas",
    // image: require("../assets/constructors/haas.png"),
    drivers: ["bearman", "ocon"],
    color: "#9D9FA2",
  },
  {
    id: "racing_bulls",
    name: "Racing Bulls",
    // image: require("../assets/constructors/alpha_tauri.png"),
    drivers: ["lawson", "hadjar"],
    color: "#6B98FF",
  },
  {
    id: "sauber",
    name: "Kick Sauber",
    // image: require("../assets/constructors/sauber.png"),
    drivers: ["hulkenberg", "bortoleto"],
    color: "#00C00F",
  },
];
