export const circuitImagesMap: Record<string, any> = {
  australia: require("../../assets/circuits/australia.webp"),
  austria: require("../../assets/circuits/austria.webp"),
  bahrain: require("../../assets/circuits/bahrain.webp"),
  belgium: require("../../assets/circuits/belgium.webp"),
  brazil: require("../../assets/circuits/brazil.webp"),
  canada: require("../../assets/circuits/canada.webp"),
  china: require("../../assets/circuits/china.webp"),
  france: require("../../assets/circuits/france.webp"),
  germany: require("../../assets/circuits/germany.webp"),
  hungary: require("../../assets/circuits/hungary.webp"),
  italy: require("../../assets/circuits/italy.webp"),
  japan: require("../../assets/circuits/japan.webp"),
  mexico: require("../../assets/circuits/mexico.webp"),
  monaco: require("../../assets/circuits/monaco.webp"),
  netherlands: require("../../assets/circuits/netherlands.webp"),
  portugal: require("../../assets/circuits/portugal.webp"),
  qatar: require("../../assets/circuits/qatar.webp"),
  russia: require("../../assets/circuits/russia.webp"),
  saudi_arabia: require("../../assets/circuits/saudi_arabia.webp"),
  singapore: require("../../assets/circuits/singapore.webp"),
  spain: require("../../assets/circuits/spain.webp"),
  turkey: require("../../assets/circuits/turkey.webp"),
};
